### ISSUE TITLE
Product backlog

### ISSUE THREAD

**Issue by juhapekkamoilanen** [TeamHaha/ohtu-miniprojekti#8]
Moi,
En näe sprintin 3 muutoksia product backlogilla. Laitatteko päivitetyn mulle näkyviin. Readme.mdssä nyt tämä linkki [https://docs.google.com/spreadsheets/d/1XbwuKcgeTLq5UjaNWDjbTOVfNu_ffJestJ7HDHrOaVU/edit#gid=1](https://docs.google.com/spreadsheets/d/1XbwuKcgeTLq5UjaNWDjbTOVfNu_ffJestJ7HDHrOaVU/edit#gid=1) 

Käsittääkseni tuo kopion luominen ei ole välttämätöntä vaan voitte jotenkin tehdä mulle view only linkin varsinaiseen backlogiin.
_J-P_

**Comment by JaakkoV** [comment]
Olet oikeassa, päivitin linkin oikeaan versioon. https://docs.google.com/spreadsheets/d/1pmqWxooi5T7qiuRcDNyEHZw4QYMUPaheOpK_FtH4GI8/
